### ISSUE TITLE
bug: mr logs -f f dies

### ISSUE THREAD

**Issue by maladon** [tadpol/MrMurano#12]
Leave MrMurano running long enough with `mr logs -f` and it eventually dies with this message:

error: can't convert nil into an exact number. Use --trace to view backtrace

**Comment by tadpol** [comment]
If you could repeat it with `--trace`, and paste that output here.

**Comment by maladon** [comment]
I'll give it a try...it takes a long time to show up

**Comment by maladon** [comment]
/Library/Ruby/Gems/2.0.0/gems/MrMurano-1.5.5/lib/MrMurano/commands/logs.rb:29:in `at': can't convert nil into an exact number (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.5.5/lib/MrMurano/commands/logs.rb:29:in `makePretty'
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.5.5/lib/MrMurano/commands/logs.rb:86:in `block (6 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.5.5/lib/MrMurano/commands/logs.rb:82:in `gsub!'
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.5.5/lib/MrMurano/commands/logs.rb:82:in `block (5 levels) in <top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:411:in `call_block'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:402:in `<<'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:106:in `read'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:284:in `block in read_body_0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:250:in `inflater'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.5.5/lib/MrMurano/commands/logs.rb:78:in `block (4 levels) in <top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1419:in `block (2 levels) in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1418:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1382:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.5.5/lib/MrMurano/commands/logs.rb:76:in `block (3 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.5.5/lib/MrMurano/http.rb:96:in `workit'
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.5.5/lib/MrMurano/http.rb:116:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.5.5/lib/MrMurano/commands/logs.rb:74:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'

**Comment by tadpol** [comment]
ok.  It looks like there must be a log entry that doesn't have a timestamp.
