### ISSUE TITLE
stack trace following logs

### ISSUE THREAD

**Issue by maladon** [tadpol/MrMurano#16]
2016-10-19 20:09:45 68.63.212.187 POST /keys/duval-principals
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse': 757: unexpected token at '{"type":"debug","timestamp":1476907785,"subject":"webservice_request","data":"08155453\",\"firstName\":\"Jimmy\",\"gender\":\"M\",\"gradeLevel\":\"4\",\"lastName\":\"Valmer\",\"middleName\":\"\",\"siteId\":\"0631\",\"studentId\":\"9999999999\",\"type\":\"Update\"},{\"badgeId\":\"9087839293\",\"firstName\":\"Frank\",\"gender\":\"M\",\"gradeLevel\":\"5\",\"lastName\":\"Fontanna\",\"middleName\":\"\",\"siteId\":\"0631\",\"studentId\":\"1234123412\",\"type\":\"New\"},{\"badgeId\":\"8237349273\",\"firstName\":\"Sue\",\"gender\":\"F\",\"gradeLevel\":\"6\",\"lastName\":\"Small\",\"middleName\":\"S\",\"siteId\":\"0901\",\"studentId\":\"9382093029\",\"type\":\"New\"},{\"badgeId\":\"4832978478\",\"firstName\":\"Sally\",\"gender\":\"F\",\"gradeLevel\":\"7\",\"lastName\":\"Smiley\",\"middleName\":\"Jane\",\"siteId\":\"0901\",\"studentId\":\"9382374954\",\"type\":\"New\"},{\"badgeId\":\"4339210928\",\"firstName\":\"Bill\",\"gender\":\"M\",\"gradeLevel\":\"7\",\"lastName\":\"Redneck\",\"middleName\":\"Bob\",\"siteId\":\"0901\",\"studentId\":\"0217383439\",\"type\":\"New\"}]"}' (JSON::ParserError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in`parse'
    from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.6.1/lib/MrMurano/commands/logs.rb:35:in `block (6 levels) in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.6.1/lib/MrMurano/commands/logs.rb:31:in`gsub!'
    from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.6.1/lib/MrMurano/commands/logs.rb:31:in `block (5 levels) in <top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:411:in`call_block'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:402:in `<<'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:106:in`read'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:313:in `read_chunked'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:276:in`block in read_body_0'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:250:in `inflater'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:274:in`read_body_0'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'
    from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.6.1/lib/MrMurano/commands/logs.rb:27:in`block (4 levels) in <top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1419:in `block (2 levels) in transport_request'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:162:in`reading_body'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1418:in `block in transport_request'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in`catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1382:in`request'
    from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.6.1/lib/MrMurano/commands/logs.rb:25:in `block (3 levels) in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.6.1/lib/MrMurano/http.rb:96:in`workit'
    from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.6.1/lib/MrMurano/http.rb:116:in `get'
    from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.6.1/lib/MrMurano/commands/logs.rb:23:in`block (2 levels) in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in`call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in`run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in`run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'

**Comment by tadpol** [comment]
This should be fixed in [v1.6.3](https://github.com/tadpol/MrMurano/releases/tag/v1.6.3), please try with that version.
