### ISSUE TITLE
Update product spec

### ISSUE THREAD

**Issue by endthestart** [tadpol/MrMurano#17]
Is it possible to update a product spec using MrMurano?

Example:

`$ mr product spec push --file spec/product.yaml`
`$ vim ... make changes to spec file`
`$ mr product spec push --file spec/product.yaml`

Results in the following error:

`Request Failed: 409: aliased resource already exists`

**Comment by tadpol** [comment]
Need to see what Murano can do at the API level. will investigate.

**Comment by tadpol** [comment]
in 8967d29e3057c245354f7ade3e0b0cf6674bdda6 spec files are now part of the syncup/syncdown   Which will do this.

**Comment by tadpol** [comment]
product specs are now part of status/syncup/syncdown  Which allows for updating which aliases exist in your product definitions.
