### ISSUE TITLE
Continuity of PID, ModelID terminology

### ISSUE THREAD

**Issue by willcharlton** [tadpol/MrMurano#19]
There seems to be a discrepancy among PID, ModelID between `mr` and the exosite.io product page.

```
$ mr product
| Label      | Type      | PID              | ModelID         |
+------------+-----------+------------------+-----------------+
| PSImonSays | onepModel | cj5nw0ndyl48to6r | 5n9taudp132qpvi |
+------------+-----------+------------------+-----------------+
```
The product ID on my exosite.io product page is 5n9taudp132qpvi.

**Comment by tadpol** [comment]
Part of this I think is from MrMurano showing all of the gory details instead of just what is useful.  So as part of fixing this, having the default to not show everything and adding an option to show all.

a5c56e4258ef171ffbe9a805fffdc2ab3a439d09
