### ISSUE TITLE
[bug] getting a stack trace trying to delete a keystore value

### ISSUE THREAD

**Issue by maladon** [tadpol/MrMurano#21]
Hubert:locker-management-platform maladon$ mr keystore delete assignments-123412341234 --trace
/Library/Ruby/Gems/2.0.0/gems/MrMurano-1.7.1/lib/MrMurano/Solution-ServiceConfig.rb:52:in `call': Unknown method: {:key=>"assignments-123412341234"} (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.7.1/lib/MrMurano/commands/keystore.rb:29:in `delkey'
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.7.1/lib/MrMurano/commands/keystore.rb:82:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'

**Comment by tadpol** [comment]
Fixed in c130c67cceab9202f495b26fbdbd53fd26ec0b1e
