### ISSUE TITLE
Syncdown asset error

### ISSUE THREAD

**Issue by ExositeJimmyLiao** [tadpol/MrMurano#26]
**Test Date:** 2016/11/29
**Environment:** version 1.8.1
**Scenario:** Syncdown asset error
**Reproduce steps:**
1. User make directory for a new project
2. User change directory to new directory
3. User use mr command to set solution id
4. User use mr command syncdown -V to download Murano solution project

**Expected result:** MrMurano successfully syncdown the project
Actual result: Assets files become a lot of code

files/index.html
![screen shot 2016-11-30 at 10 24 54 am](https://cloud.githubusercontent.com/assets/20276431/20737392/4825b2d6-b6e7-11e6-830d-8a21aff5628e.png)

**Comment by tadpol** [comment]
Looks like an API changed.  I'll dig in.

**Comment by tadpol** [comment]
This maybe a bug in Murano. It is being checked on now.

**Comment by tadpol** [comment]
Murano has this fixed now.  Syncdown of static files should be working again.

**Comment by ExositeJimmyLiao** [comment]
![Uploading Screen Shot 2016-12-16 at 1.25.47 PM.png…](screen-shot-now)
syncdown is working now, thank you.
