### ISSUE TITLE
error attempting to use tsw

### ISSUE THREAD

**Issue by maladon** [tadpol/MrMurano#3]
here's my command:
mr tsw "insert raw_data rid=10c409ec279aeafaabb726010b13199221e47877,pid=iznvk5tonpadobt9,alias=bay_access_list,device_sn=12345 data"

this is what I get in response:
got #<Net::HTTPBadRequest:0x007ff6eaa2dcd8> from #<Net::HTTP::Post:0x007ff6eaa1c0c8>
https://bizapi.hosted.exosite.io/api:1/solution/veIq4O5Zt0/serviceconfig/81f56ce4-6bb0-11e6-b185-057e87066281/call/write
:: {"statusCode":400,"message":"Service Call Error: Missing parameter query for operation write in service timeseries","code":"BadRequestError"}
===

**Comment by tadpol** [comment]
Fixed in ac3136d
