### ISSUE TITLE
Add a password sub-command

### ISSUE THREAD

**Issue by tadpol** [tadpol/MrMurano#31]
Add a password sub-command for changing and deleting saved passwords.

**Comment by ExositeJimmyLiao** [comment]
Ali, Frank and I meet this issue today.
And we spend a lot of time finding the method to logout.
Finally, we delete ~/.mrmuranorc and login again.

**Comment by jcfrank** [comment]
Just a clarification of what Jimmy and I encountered.
After installing mrmurano, I ran `business list` for the first time, but missed the `@exosite.com` in my account name.
Then the error message:
```
User name: frankchen
Request Failed: 400: [400] child "email" fails because ["email" must be a valid email]
Check to see if username and password are correct.
error: no implicit conversion of nil into String. Use --trace to view backtrace
```

After that, we couldn't find documents or suitable commands to change my account name or to log out.
Had to dive into source code to find out the config file `~/.mrmuranorc`, and to remove the `name = frankchen` to login again.
