### ISSUE TITLE
Bug: syncdown reports "error: no implicit conversion of Symbol into Integer. Use --trace to view backtrace"

### ISSUE THREAD

**Issue by dominicletz** [tadpol/MrMurano#36]
Calling "mr syncdown -V --trace" leads to:

```
$ mr syncdown -V --trace
Updating item GET_/api:1/session
Updating item WEBSOCKET_/device
Updating item PUT_/api:1/reset
Updating item WEBSOCKET_/api:1/phone
Updating item WEBSOCKET_/_test
Updating item POST_/api:1/session
Updating item GET_/api:1/reset_verify/{code}
Updating item GET_/api:1/verify/{code}
Updating item WEBSOCKET_/device_debug
Updating item WEBSOCKET_/console
Updating item POST_/api:1/reset
Updating item PUT_/api:1/user/{email}
Updating item /devicetest.html
Updating item /
Updating item funcs
Updating item phone
Updating item my_library
Updating item test
Updating item device
Updating item user
Updating item auth
Updating item errors
/var/lib/gems/2.3.0/gems/MrMurano-1.10.1/lib/MrMurano/Solution-Services.rb:39:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/MrMurano-1.10.1/lib/MrMurano/Solution-Services.rb:39:in `fetch'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.10.1/lib/MrMurano/SyncUpDown.rb:176:in `block in download'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.10.1/lib/MrMurano/SyncUpDown.rb:175:in `open'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.10.1/lib/MrMurano/SyncUpDown.rb:175:in `open'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.10.1/lib/MrMurano/SyncUpDown.rb:175:in `download'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.10.1/lib/MrMurano/SyncUpDown.rb:363:in `block in syncdown'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.10.1/lib/MrMurano/SyncUpDown.rb:359:in `each'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.10.1/lib/MrMurano/SyncUpDown.rb:359:in `syncdown'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.10.1/lib/MrMurano/commands/sync.rb:25:in `block (3 levels) in <top (required)>'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.10.1/lib/MrMurano/SyncUpDown.rb:34:in `block in each_filtered'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.10.1/lib/MrMurano/SyncUpDown.rb:32:in `each'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.10.1/lib/MrMurano/SyncUpDown.rb:32:in `each_filtered'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.10.1/lib/MrMurano/commands/sync.rb:23:in `block (2 levels) in <top (required)>'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by tadpol** [comment]
This maybe related to #37.

**Comment by dominicletz** [comment]
Still there with 1.11.1

`Updating item GET_/api:1/session
Updating item WEBSOCKET_/device
Updating item PUT_/api:1/reset
Updating item WEBSOCKET_/api:1/phone
Updating item WEBSOCKET_/_test
Updating item POST_/api:1/session
Updating item GET_/api:1/reset_verify/{code}
Updating item GET_/api:1/verify/{code}
Updating item WEBSOCKET_/device_debug
Updating item WEBSOCKET_/console
Updating item POST_/api:1/reset
Updating item PUT_/api:1/user/{email}
Updating item /devicetest.html
Updating item /
Updating item funcs
Updating item phone
Updating item my_library
Updating item test
Updating item device
Updating item user
Updating item auth
Updating item errors
/var/lib/gems/2.3.0/gems/MrMurano-1.11.1/lib/MrMurano/Solution-Services.rb:32:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/MrMurano-1.11.1/lib/MrMurano/Solution-Services.rb:32:in `fetch'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.11.1/lib/MrMurano/SyncUpDown.rb:181:in `block in download'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.11.1/lib/MrMurano/SyncUpDown.rb:180:in `open'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.11.1/lib/MrMurano/SyncUpDown.rb:180:in `open'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.11.1/lib/MrMurano/SyncUpDown.rb:180:in `download'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.11.1/lib/MrMurano/SyncUpDown.rb:371:in `block in syncdown'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.11.1/lib/MrMurano/SyncUpDown.rb:367:in `each'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.11.1/lib/MrMurano/SyncUpDown.rb:367:in `syncdown'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.11.1/lib/MrMurano/commands/sync.rb:25:in `block (3 levels) in <top (required)>'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.11.1/lib/MrMurano/SyncUpDown.rb:34:in `block in each_filtered'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.11.1/lib/MrMurano/SyncUpDown.rb:32:in `each'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.11.1/lib/MrMurano/SyncUpDown.rb:32:in `each_filtered'
	from /var/lib/gems/2.3.0/gems/MrMurano-1.11.1/lib/MrMurano/commands/sync.rb:23:in `block (2 levels) in <top (required)>'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'`

**Comment by tadpol** [comment]
ok. strange. I wonder if there is something special about the module 'errors'

I'll try to reproduce this.
