### ISSUE TITLE
Support `syncup` for only 1 endpoint

### ISSUE THREAD

**Issue by akiratsai** [tadpol/MrMurano#46]
When I want to test the endpoint I just wrote, I need to run `mr push -a --update` rather than specify the endpoint I wrote only. And also `diff` all endpoints is so slow when there are a lot endpoints in a solution.

**Comment by tadpol** [comment]
How many is "a lot endpoints"?

**Comment by akiratsai** [comment]
@tadpol There are 67 endpoints in my solution right now.

**Comment by tadpol** [comment]
I am separating the ability to do this and the performance of it.

**Comment by akiratsai** [comment]
@tadpol Sounds good to me, it's not that slow, and can be improve later.
