### ISSUE TITLE
Suport Murano create solution

### ISSUE THREAD

**Issue by ExositeJimmyLiao** [tadpol/MrMurano#52]
In Murano solution, user can create solution by a template URL.
But Sphinx API follow Exosite CLI's `Solutionfile.json` to create a solution,
user can't create a solution by a MrMurano Project.

MrMurano Project:
[https://github.com/ExositeJimmyLiao/Murano-2016-Bootcamp-MrMurano](https://github.com/ExositeJimmyLiao/Murano-2016-Bootcamp-MrMurano)
Solutionfile.json:
[https://github.com/ExositeJimmyLiao/Murano-2016-Bootcamp-Full/blob/master/Solutionfile.json](https://github.com/ExositeJimmyLiao/Murano-2016-Bootcamp-Full/blob/master/Solutionfile.json)

**Comment by tadpol** [comment]
The command to export a `Solutionfile.json` is `mr config export`  This will also collect all of the endpoints into a single file.
