### ISSUE TITLE
Some dependencies missing

### ISSUE THREAD

**Issue by ctv-vijay** [tadpol/MrMurano#53]
Hi,

I've installed ruby 1.9.3p194 (2012-04-20 revision 35410) [arm-linux-eabihf], gem 1.8.23 and MrMurano.
When I try running "mr", I get errors:

# mr
/var/lib/gems/1.9.1/gems/commander-4.4.3/lib/commander/runner.rb:409:in `block in require_program': program version required (Commander::Runner::CommandError)
        from /var/lib/gems/1.9.1/gems/commander-4.4.3/lib/commander/runner.rb:408:in `each'
        from /var/lib/gems/1.9.1/gems/commander-4.4.3/lib/commander/runner.rb:408:in `require_program'
        from /var/lib/gems/1.9.1/gems/commander-4.4.3/lib/commander/runner.rb:52:in `run!'
        from /var/lib/gems/1.9.1/gems/commander-4.4.3/lib/commander/delegates.rb:19:in `run!'
        from /var/lib/gems/1.9.1/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /var/lib/gems/1.9.1/gems/MrMurano-1.12.6/lib/MrMurano/commands/logs.rb:31: invalid group name <0>: /\{(?>[^}{]+|\g<0>)*\}/m (SyntaxError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/MrMurano-1.12.6/lib/MrMurano/commands.rb:11:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/MrMurano-1.12.6/lib/MrMurano.rb:17:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/MrMurano-1.12.6/bin/mr:6:in `<top (required)>'
        from /usr/local/bin/mr:23:in `load'
        from /usr/local/bin/mr:23:in `<main>'

This is an embedded gateway running debian linux (Linux Moxa 4.1.0-uc8100-me+ #1 SMP Wed Mar 9 11:19:03 CST 2016 armv7l GNU/Linux). It also has Python 2.7.3 with pip 8.1.2.

Kind regards,
Vijay.

**Comment by tadpol** [comment]
You need ruby 2.0.

**Comment by ctv-vijay** [comment]
Thanks.
