### ISSUE TITLE
mr logs -f doesn't return all the lines

### ISSUE THREAD

**Issue by maladon** [tadpol/MrMurano#8]
In my route I have many print statements, I see them all in murano. I see only some in mr logs -f

**Comment by tadpol** [comment]
Do they appear when running without the `-f` option?

**Comment by maladon** [comment]
No.

**Comment by tadpol** [comment]
Found. The logs request only has a timestamp resolution of 1sec, and so multiple logs entries can have the same timestamp.

Currently, MrMurano is using the timestamp to be smarter about what to display across multiple fetches.  So need to change the way that works.

**Comment by maladon** [comment]
That'll do it.

It seems even the Murano platform has a similar issue. sometimes multiple print statements show up as a single log entry.

(I submitted a bug and they have it on their list now)

**Comment by tadpol** [comment]
Should be fixed in b3370eb1c8dd34aeea3f

**Comment by maladon** [comment]
ahhhhhh....

so much better!
